!procedure $api()
Container(api, "api: API", "Python", "REST API для работы с каталогом и пользователями")
!endprocedure

!procedure $db()
ContainerDb(db, "db: База данных", "MongoDB/mongod", "Хранит все данные")
!endprocedure

!procedure $router()
Container(router, "db_router: Роутер запросов к БД", "MongoDB/mongos", "Маршрутизирует запросы к кластеру БД")
!endprocedure

!procedure $cfg()
ContainerDb(cfg, "db_cfg: Конфигурация БД", "MongoDB/mongod", "Хранит метаданные кластера БД")
!endprocedure

!procedure $cfg1()
ContainerDb(cfg_1, "db_cfg_1: Конфигурация БД 1 (Primary)", "MongoDB/mongod", "Хранит метаданные кластера БД")
!endprocedure

!procedure $cfg2()
ContainerDb(cfg_2, "db_cfg_2: Конфигурация БД 2", "MongoDB/mongod", "Хранит метаданные кластера БД")
!endprocedure

!procedure $cfg3()
ContainerDb(cfg_3, "db_cfg_3: Конфигурация БД 3", "MongoDB/mongod", "Хранит метаданные кластера БД")
!endprocedure

!procedure $cfgRs()
$cfg1()
$cfg2()
$cfg3()
!endprocedure

!procedure $shard1()
ContainerDb(shard_1, "db_shard_1: Шард БД 1", "MongoDB/mongod", "Хранит часть данных")
!endprocedure

!procedure $shard2()
ContainerDb(shard_2, "db_shard_2: Шард БД 2", "MongoDB/mongod", "Хранит часть данных")
!endprocedure

!procedure $shard1R1()
ContainerDb(shard_1_1, "db_shard_1_1: Шард БД 1, реплика 1 (Primary)", "MongoDB/mongod", "Хранит часть данных")
!endprocedure

!procedure $shard1R2()
ContainerDb(shard_1_2, "db_shard_1_2: Шард БД 1, реплика 2", "MongoDB/mongod", "Хранит часть данных")
!endprocedure

!procedure $shard1R3()
ContainerDb(shard_1_3, "db_shard_1_3: Шард БД 1, реплика 3", "MongoDB/mongod", "Хранит часть данных")
!endprocedure

!procedure $shard2R1()
ContainerDb(shard_2_1, "db_shard_2_1: Шард БД 2, реплика 1 (Primary)", "MongoDB/mongod", "Хранит часть данных")
!endprocedure

!procedure $shard2R2()
ContainerDb(shard_2_2, "db_shard_2_2: Шард БД 2, реплика 2", "MongoDB/mongod", "Хранит часть данных")
!endprocedure

!procedure $shard2R3()
ContainerDb(shard_2_3, "db_shard_2_3: Шард БД 2, реплика 3", "MongoDB/mongod", "Хранит часть данных")
!endprocedure

!procedure $shard1Rs()
$shard1R1()
$shard1R2()
$shard1R3()
!endprocedure

!procedure $shard2Rs()
$shard2R1()
$shard2R2()
$shard2R3()
!endprocedure

!procedure $cache()
Container(cache, "cache: Кэш", "Redis", "Кэширует ответы GET /<collection>/users")
!endprocedure
