@startuml
!pragma layout smetana

!include <C4/C4_Container>
!include _containers.puml

title Мобильный мир: горизонтальное масштабирование (Service Discovery и API Gateway)

left to right direction

System_Boundary(mobileWorld, "Мобильный мир") {
    $apiGtw()
    $apis()
    $router()
    $cache()
    $cfgRs()
    $shard1Rs()
    $shard2Rs()
    $sdRs()
}

Rel_D(api_gtw, api_1, "Балансирует трафик", "HTTP")
Rel_D(api_gtw, api_2, "Балансирует трафик", "HTTP")

Rel_D(api_gtw, sd_1, "Получает список здоровых инстансов", "HTTP API")

Rel_U(api_1, sd_1, "Регистрирует сервис и health-check", "HTTP API")
Rel_U(api_2, sd_1, "Регистрирует сервис и health-check", "HTTP API")

Rel_D(api_1, router, "Отправляет запросы на чтение и запись", "MongoDB Wire Protocol")
Rel_D(api_2, router, "Отправляет запросы на чтение и запись", "MongoDB Wire Protocol")

Rel_R(api_1, cache, "Читает и заполняет кэш (cache-aside, TTL 60 с)", "RESP")
Rel_L(api_2, cache, "Читает и заполняет кэш (cache-aside, TTL 60 с)", "RESP")

Rel_R(sd_1, sd_2, "Реплицирует состояние (Raft)")
Rel_L(sd_1, sd_3, "Реплицирует состояние (Raft)")

Rel_D(router, cfg_1, "Читает метаданные")
Rel_D(router, cfg_2, "Читает метаданные")
Rel_D(router, cfg_3, "Читает метаданные")

Rel_D(router, shard_1_1, "Читает и записывает данные")
Rel_D(router, shard_2_1, "Читает и записывает данные")

Rel_D(router, shard_1_2, "Читает данные")
Rel_D(router, shard_1_3, "Читает данные")
Rel_D(router, shard_2_2, "Читает данные")
Rel_D(router, shard_2_3, "Читает данные")

Rel_R(cfg_1, cfg_2, "Реплицирует данные")
Rel_L(cfg_1, cfg_3, "Реплицирует данные")

Rel_R(shard_1_1, shard_1_2, "Реплицирует данные")
Rel_L(shard_1_1, shard_1_3, "Реплицирует данные")
Rel_R(shard_2_1, shard_2_2, "Реплицирует данные")
Rel_L(shard_2_1, shard_2_3, "Реплицирует данные")

@enduml
